"""seven pillars

Revision ID: 5ccf2b58d02a
Revises: 
Create Date: 2026-03-22 16:42:00.428989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ccf2b58d02a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domains',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('state_checkins',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('checkin_type', sa.String(), nullable=False),
    sa.Column('energy_level', sa.Integer(), nullable=True),
    sa.Column('mood', sa.Integer(), nullable=True),
    sa.Column('focus_level', sa.Integer(), nullable=True),
    sa.Column('freeform_note', sa.Text(), nullable=True),
    sa.Column('context', sa.String(), nullable=True),
    sa.Column('logged_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("checkin_type IN ('morning', 'midday', 'evening', 'micro', 'freeform')", name='ck_state_checkins_type'),
    sa.CheckConstraint('energy_level BETWEEN 1 AND 5 OR energy_level IS NULL', name='ck_state_checkins_energy_level'),
    sa.CheckConstraint('focus_level BETWEEN 1 AND 5 OR focus_level IS NULL', name='ck_state_checkins_focus_level'),
    sa.CheckConstraint('mood BETWEEN 1 AND 5 OR mood IS NULL', name='ck_state_checkins_mood'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('goals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('domain_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active', 'paused', 'achieved', 'abandoned')", name='ck_goals_status'),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('routines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('domain_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('frequency', sa.String(), nullable=False),
    sa.Column('current_streak', sa.Integer(), nullable=False),
    sa.Column('best_streak', sa.Integer(), nullable=False),
    sa.Column('last_completed', sa.Date(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('energy_cost', sa.Integer(), nullable=True),
    sa.Column('activation_friction', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("frequency IN ('daily', 'weekdays', 'weekends', 'weekly', 'custom')", name='ck_routines_frequency'),
    sa.CheckConstraint("status IN ('active', 'paused', 'retired')", name='ck_routines_status'),
    sa.CheckConstraint('activation_friction BETWEEN 1 AND 5 OR activation_friction IS NULL', name='ck_routines_activation_friction'),
    sa.CheckConstraint('energy_cost BETWEEN 1 AND 5 OR energy_cost IS NULL', name='ck_routines_energy_cost'),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_routines_status', 'routines', ['status'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('goal_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('progress_pct', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('not_started', 'active', 'blocked', 'completed', 'abandoned')", name='ck_projects_status'),
    sa.CheckConstraint('progress_pct >= 0 AND progress_pct <= 100', name='ck_projects_progress_pct'),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('routine_schedule',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('routine_id', sa.UUID(), nullable=False),
    sa.Column('day_of_week', sa.String(), nullable=True),
    sa.Column('time_of_day', sa.String(), nullable=True),
    sa.Column('preferred_window', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['routine_id'], ['routines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('cognitive_type', sa.String(), nullable=True),
    sa.Column('energy_cost', sa.Integer(), nullable=True),
    sa.Column('activation_friction', sa.Integer(), nullable=True),
    sa.Column('context_required', sa.String(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('recurrence_rule', sa.String(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("cognitive_type IN ('hands_on', 'communication', 'decision', 'errand', 'admin', 'focus_work') OR cognitive_type IS NULL", name='ck_tasks_cognitive_type'),
    sa.CheckConstraint("status IN ('pending', 'active', 'completed', 'skipped', 'deferred')", name='ck_tasks_status'),
    sa.CheckConstraint('activation_friction BETWEEN 1 AND 5 OR activation_friction IS NULL', name='ck_tasks_activation_friction'),
    sa.CheckConstraint('energy_cost BETWEEN 1 AND 5 OR energy_cost IS NULL', name='ck_tasks_energy_cost'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tasks_cognitive_type', 'tasks', ['cognitive_type'], unique=False)
    op.create_index('ix_tasks_energy_cost', 'tasks', ['energy_cost'], unique=False)
    op.create_index('ix_tasks_status', 'tasks', ['status'], unique=False)
    op.create_table('activity_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.Column('routine_id', sa.UUID(), nullable=True),
    sa.Column('checkin_id', sa.UUID(), nullable=True),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('energy_before', sa.Integer(), nullable=True),
    sa.Column('energy_after', sa.Integer(), nullable=True),
    sa.Column('mood_rating', sa.Integer(), nullable=True),
    sa.Column('friction_actual', sa.Integer(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('logged_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("action_type IN ('completed', 'skipped', 'deferred', 'started', 'reflected', 'checked_in')", name='ck_activity_log_action_type'),
    sa.CheckConstraint('energy_after BETWEEN 1 AND 5 OR energy_after IS NULL', name='ck_activity_log_energy_after'),
    sa.CheckConstraint('energy_before BETWEEN 1 AND 5 OR energy_before IS NULL', name='ck_activity_log_energy_before'),
    sa.CheckConstraint('friction_actual BETWEEN 1 AND 5 OR friction_actual IS NULL', name='ck_activity_log_friction_actual'),
    sa.CheckConstraint('mood_rating BETWEEN 1 AND 5 OR mood_rating IS NULL', name='ck_activity_log_mood_rating'),
    sa.ForeignKeyConstraint(['checkin_id'], ['state_checkins.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['routine_id'], ['routines.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_activity_log_logged_at', 'activity_log', ['logged_at'], unique=False)
    op.create_table('task_tags',
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_tags')
    op.drop_index('ix_activity_log_logged_at', table_name='activity_log')
    op.drop_table('activity_log')
    op.drop_index('ix_tasks_status', table_name='tasks')
    op.drop_index('ix_tasks_energy_cost', table_name='tasks')
    op.drop_index('ix_tasks_cognitive_type', table_name='tasks')
    op.drop_table('tasks')
    op.drop_table('routine_schedule')
    op.drop_table('projects')
    op.drop_index('ix_routines_status', table_name='routines')
    op.drop_table('routines')
    op.drop_table('goals')
    op.drop_table('tags')
    op.drop_table('state_checkins')
    op.drop_table('domains')
    # ### end Alembic commands ###
